### ISSUE TITLE
01_pipeline processing fails to run

### ISSUE THREAD

**Issue by hapion1** [joLahann/mppn#2]
Hi,
everything is installed as instructed and should work. But notebook 01_pipeline cannot run. here's the screenshot with the error:
![image](https://user-images.githubusercontent.com/91491095/137794304-e4b1cf9f-a27f-47bb-bfe0-147933e9b857.png)

I cannot find any library containing 'CudaCallback'. Where should it be located?

**Comment by joLahann** [comment]
Hi,
The CudaCallback is part of the fastai library.

**Comment by hapion1** [comment]
Okay. Because of the NameError it seems like it does not import the 'CudaCallback' function. Any idea how to fix it or what the problem is?

**Comment by joLahann** [comment]
There is a new fastai release, that changed some functions. I added explicit versions to the used packages in the settings.ini. If you pull the latest updates and rerun python setup.py install it should work now.

**Comment by hapion1** [comment]
Yes! Thanks!
