### ISSUE TITLE
How to resume training?

### ISSUE THREAD

**Issue by abhinav-bohra** [joLahann/mppn#4]
Hello, thanks for providing the codes. 

How can I resume training in case my code crashes in between?

For example - if I run prediction_evaluation.py for 5 event_logs & 3 ppms and let's say the code crashes after (2nd log, 1st ppm, 1st task). How do I resume training from there?

**Comment by joLahann** [comment]
Hi,
Resume training is currently not supported. However, you can manually pick which logs and models to train.

**Comment by abhinav-bohra** [comment]
Okay understood. Thank you!
